### PR TITLE
Minor cleanup; PEP8 compliance

### PR DESCRIPTION
**Pull request by maxcountryman**
This commit set provides removal of unused imports and brings the codebase into alignment with PEP8 standards, i.e. `$ pep8 nrepl` runs cleanly after this.

### CODE REVIEW

**Comment by cemerick** [comment]
gah, the eliminating the space between fn names and arg tuples hurts. :-/

Could you squash these changes down to one commit?

**Comment by maxcountryman** [comment]
You certainly don't have to abide by PEP8, so it's totally up to you if you want to merge this or not. :)

**Comment by cemerick** [comment]
Insofar as I'd much rather have a _real_ python programmer take it over eventually, I presume it wouldn't hurt. :-)

Will take a look tomorrow and almost certainly merge.

**Comment by maxcountryman** [comment]
Cool, thanks! And yes, standardizing against PEP8 usually helps encourage people to wade through Python-related code, ime. :)

**Pull request merged**
